# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:40:25+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class DepthChart(BaseModel):
    DepthChartID: Optional[int] = None
    DepthOrder: Optional[int] = None
    Name: Optional[str] = None
    PlayerID: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    TeamID: Optional[int] = None
    Updated: Optional[str] = None


class DfsSlatePlayer(BaseModel):
    OperatorPlayerID: Optional[str] = None
    OperatorPlayerName: Optional[str] = None
    OperatorPosition: Optional[str] = None
    OperatorRosterSlots: Optional[List[str]] = None
    OperatorSalary: Optional[int] = None
    OperatorSlatePlayerID: Optional[str] = None
    PlayerGameProjectionStatID: Optional[int] = None
    PlayerID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None
    SlatePlayerID: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None


class Lineup(BaseModel):
    Confirmed: Optional[bool] = None
    FirstName: Optional[str] = None
    LastName: Optional[str] = None
    PlayerID: Optional[int] = None
    Position: Optional[str] = None
    Starting: Optional[bool] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None


class Player(BaseModel):
    BirthCity: Optional[str] = None
    BirthCountry: Optional[str] = None
    BirthDate: Optional[str] = None
    BirthState: Optional[str] = None
    College: Optional[str] = None
    DepthChartOrder: Optional[int] = None
    DepthChartPosition: Optional[str] = None
    DraftKingsName: Optional[str] = None
    DraftKingsPlayerID: Optional[int] = None
    Experience: Optional[int] = None
    FanDuelName: Optional[str] = None
    FanDuelPlayerID: Optional[int] = None
    FantasyAlarmPlayerID: Optional[int] = None
    FantasyDraftName: Optional[str] = None
    FantasyDraftPlayerID: Optional[int] = None
    FirstName: Optional[str] = None
    GlobalTeamID: Optional[int] = None
    Height: Optional[int] = None
    HighSchool: Optional[str] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    Jersey: Optional[int] = None
    LastName: Optional[str] = None
    NbaDotComPlayerID: Optional[int] = None
    PhotoUrl: Optional[str] = None
    PlayerID: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    RotoWirePlayerID: Optional[int] = None
    RotoworldPlayerID: Optional[int] = None
    Salary: Optional[int] = None
    SportRadarPlayerID: Optional[str] = None
    SportsDataID: Optional[str] = None
    SportsDirectPlayerID: Optional[int] = None
    StatsPlayerID: Optional[int] = None
    Status: Optional[str] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    UsaTodayHeadshotNoBackgroundUpdated: Optional[str] = None
    UsaTodayHeadshotNoBackgroundUrl: Optional[str] = None
    UsaTodayHeadshotUpdated: Optional[str] = None
    UsaTodayHeadshotUrl: Optional[str] = None
    UsaTodayPlayerID: Optional[int] = None
    Weight: Optional[int] = None
    XmlTeamPlayerID: Optional[int] = None
    YahooName: Optional[str] = None
    YahooPlayerID: Optional[int] = None


class PlayerGameProjection(BaseModel):
    Assists: Optional[float] = None
    AssistsPercentage: Optional[float] = None
    BlockedShots: Optional[float] = None
    BlocksPercentage: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DefensiveRebounds: Optional[float] = None
    DefensiveReboundsPercentage: Optional[float] = None
    DoubleDoubles: Optional[float] = None
    DraftKingsPosition: Optional[str] = None
    DraftKingsSalary: Optional[int] = None
    EffectiveFieldGoalsPercentage: Optional[float] = None
    FanDuelPosition: Optional[str] = None
    FanDuelSalary: Optional[int] = None
    FantasyDataSalary: Optional[int] = None
    FantasyDraftPosition: Optional[str] = None
    FantasyDraftSalary: Optional[int] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalsAttempted: Optional[float] = None
    FieldGoalsMade: Optional[float] = None
    FieldGoalsPercentage: Optional[float] = None
    FreeThrowsAttempted: Optional[float] = None
    FreeThrowsMade: Optional[float] = None
    FreeThrowsPercentage: Optional[float] = None
    GameID: Optional[int] = None
    Games: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalOpponentID: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    HomeOrAway: Optional[str] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    IsClosed: Optional[bool] = None
    IsGameOver: Optional[bool] = None
    LineupConfirmed: Optional[bool] = None
    LineupStatus: Optional[str] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OffensiveRebounds: Optional[float] = None
    OffensiveReboundsPercentage: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    OpponentPositionRank: Optional[int] = None
    OpponentRank: Optional[int] = None
    PersonalFouls: Optional[float] = None
    PlayerEfficiencyRating: Optional[float] = None
    PlayerID: Optional[int] = None
    PlusMinus: Optional[float] = None
    Points: Optional[float] = None
    Position: Optional[str] = None
    Rebounds: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Seconds: Optional[int] = None
    Started: Optional[int] = None
    StatID: Optional[int] = None
    Steals: Optional[float] = None
    StealsPercentage: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    ThreePointersAttempted: Optional[float] = None
    ThreePointersMade: Optional[float] = None
    ThreePointersPercentage: Optional[float] = None
    TotalReboundsPercentage: Optional[float] = None
    TripleDoubles: Optional[float] = None
    TrueShootingAttempts: Optional[float] = None
    TrueShootingPercentage: Optional[float] = None
    TurnOversPercentage: Optional[float] = None
    Turnovers: Optional[float] = None
    TwoPointersAttempted: Optional[float] = None
    TwoPointersMade: Optional[float] = None
    TwoPointersPercentage: Optional[float] = None
    Updated: Optional[str] = None
    UsageRatePercentage: Optional[float] = None
    YahooPosition: Optional[str] = None
    YahooSalary: Optional[int] = None


class PlayerSeasonProjection(BaseModel):
    Assists: Optional[float] = None
    AssistsPercentage: Optional[float] = None
    BlockedShots: Optional[float] = None
    BlocksPercentage: Optional[float] = None
    DefensiveRebounds: Optional[float] = None
    DefensiveReboundsPercentage: Optional[float] = None
    DoubleDoubles: Optional[float] = None
    EffectiveFieldGoalsPercentage: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalsAttempted: Optional[float] = None
    FieldGoalsMade: Optional[float] = None
    FieldGoalsPercentage: Optional[float] = None
    FreeThrowsAttempted: Optional[float] = None
    FreeThrowsMade: Optional[float] = None
    FreeThrowsPercentage: Optional[float] = None
    Games: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    IsClosed: Optional[bool] = None
    LineupConfirmed: Optional[bool] = None
    LineupStatus: Optional[str] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OffensiveRebounds: Optional[float] = None
    OffensiveReboundsPercentage: Optional[float] = None
    PersonalFouls: Optional[float] = None
    PlayerEfficiencyRating: Optional[float] = None
    PlayerID: Optional[int] = None
    PlusMinus: Optional[float] = None
    Points: Optional[float] = None
    Position: Optional[str] = None
    Rebounds: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Seconds: Optional[int] = None
    Started: Optional[int] = None
    StatID: Optional[int] = None
    Steals: Optional[float] = None
    StealsPercentage: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    ThreePointersAttempted: Optional[float] = None
    ThreePointersMade: Optional[float] = None
    ThreePointersPercentage: Optional[float] = None
    TotalReboundsPercentage: Optional[float] = None
    TripleDoubles: Optional[float] = None
    TrueShootingAttempts: Optional[float] = None
    TrueShootingPercentage: Optional[float] = None
    TurnOversPercentage: Optional[float] = None
    Turnovers: Optional[float] = None
    TwoPointersAttempted: Optional[float] = None
    TwoPointersMade: Optional[float] = None
    TwoPointersPercentage: Optional[float] = None
    Updated: Optional[str] = None
    UsageRatePercentage: Optional[float] = None


class Quarter(BaseModel):
    AwayScore: Optional[int] = None
    GameID: Optional[int] = None
    HomeScore: Optional[int] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    QuarterID: Optional[int] = None


class Series(BaseModel):
    AwayTeamWins: Optional[int] = None
    GameNumber: Optional[int] = None
    HomeTeamWins: Optional[int] = None
    MaxLength: Optional[int] = None


class StartingLineups(BaseModel):
    AwayLineup: Optional[List[Lineup]] = None
    AwayTeam: Optional[str] = None
    AwayTeamID: Optional[int] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    GameID: Optional[int] = None
    HomeLineup: Optional[List[Lineup]] = None
    HomeTeam: Optional[str] = None
    HomeTeamID: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Status: Optional[str] = None


class TeamDepthChart(BaseModel):
    DepthCharts: Optional[List[DepthChart]] = None
    TeamID: Optional[int] = None


class FieldFormatDepthChartsGetResponse(RootModel[List[TeamDepthChart]]):
    root: List[TeamDepthChart]


class Format(Enum):
    XML = 'XML'
    JSON = 'JSON'


class FieldFormatInjuredPlayersGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatPlayerGameProjectionStatsByDateDateGetResponse(
    RootModel[List[PlayerGameProjection]]
):
    root: List[PlayerGameProjection]


class FieldFormatPlayerSeasonProjectionStatsSeasonGetResponse(
    RootModel[List[PlayerSeasonProjection]]
):
    root: List[PlayerSeasonProjection]


class FieldFormatPlayerSeasonProjectionStatsByTeamSeasonTeamGetResponse(
    RootModel[List[PlayerSeasonProjection]]
):
    root: List[PlayerSeasonProjection]


class FieldFormatStartingLineupsByDateDateGetResponse(RootModel[List[StartingLineups]]):
    root: List[StartingLineups]


class Game(BaseModel):
    AlternateID: Optional[int] = None
    Attendance: Optional[int] = None
    AwayRotationNumber: Optional[int] = None
    AwayTeam: Optional[str] = None
    AwayTeamID: Optional[int] = None
    AwayTeamMoneyLine: Optional[int] = None
    AwayTeamScore: Optional[int] = None
    Channel: Optional[str] = None
    CrewChiefID: Optional[int] = None
    DateTime: Optional[str] = None
    DateTimeUTC: Optional[str] = None
    Day: Optional[str] = None
    GameEndDateTime: Optional[str] = None
    GameID: Optional[int] = None
    GlobalAwayTeamID: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalHomeTeamID: Optional[int] = None
    HomeRotationNumber: Optional[int] = None
    HomeTeam: Optional[str] = None
    HomeTeamID: Optional[int] = None
    HomeTeamMoneyLine: Optional[int] = None
    HomeTeamScore: Optional[int] = None
    IsClosed: Optional[bool] = None
    LastPlay: Optional[str] = None
    NeutralVenue: Optional[bool] = None
    OverPayout: Optional[int] = None
    OverUnder: Optional[float] = None
    PointSpread: Optional[float] = None
    PointSpreadAwayTeamMoneyLine: Optional[int] = None
    PointSpreadHomeTeamMoneyLine: Optional[int] = None
    Quarter: Optional[str] = None
    Quarters: Optional[List[Quarter]] = None
    RefereeID: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    SeriesInfo: Optional[Series] = None
    StadiumID: Optional[int] = None
    Status: Optional[str] = None
    TimeRemainingMinutes: Optional[int] = None
    TimeRemainingSeconds: Optional[int] = None
    UmpireID: Optional[int] = None
    UnderPayout: Optional[int] = None
    Updated: Optional[str] = None


class DfsSlateGame(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    GameID: Optional[int] = None
    OperatorGameID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None


class DfsSlate(BaseModel):
    DfsSlateGames: Optional[List[DfsSlateGame]] = None
    DfsSlatePlayers: Optional[List[DfsSlatePlayer]] = None
    IsMultiDaySlate: Optional[bool] = None
    NumberOfGames: Optional[int] = None
    Operator: Optional[str] = None
    OperatorDay: Optional[str] = None
    OperatorGameType: Optional[str] = None
    OperatorName: Optional[str] = None
    OperatorSlateID: Optional[int] = None
    OperatorStartTime: Optional[str] = None
    RemovedByOperator: Optional[bool] = None
    SalaryCap: Optional[int] = None
    SlateID: Optional[int] = None
    SlateRosterSlots: Optional[List[str]] = None


class FieldFormatDfsSlatesByDateDateGetResponse(RootModel[List[DfsSlate]]):
    root: List[DfsSlate]
